### Comparing Sidak and Simes
# Perform simulation to compare the Sidak and Simes test for the global null
# power is 1-beta, where beta is type II error
for(m in c(10^2,10^4)){
  for(p in c(0.05,0.1,0.2)){
    a= 0.01
    sidak = 0
    proportion_sidak = 0
    simes = 0
    proportion_simes = 0
    for (theta in seq(0.1,10, by = 0.2 )){
      for( b in 1:200){
        sidak_sum = 0
        simes_sum = 0
        m_1 = p*m
        star_a = 1-(1-a)^(1/m)
        sequence = c(numeric(m_1)+theta,numeric(m-m_1))
        z = rnorm(m,sequence,1)
        z_value = qnorm(1-star_a)
        for(i in (1:m_1)){
          sidak_sum = sidak_sum + sum(z[i] > z_value)
        }
        proportion_sidak = c(proportion_sidak,sidak_sum/m_1)
        order = rank(z)
        z_value = 0
        for(i in order[1:m_1]){
          z_value = c(z_value,-qnorm(i*a/m))
        }
        z_value = z_value[-1]
        for(i in 1:m_1){
          if (z[i] <= z_value[i]){
            simes_sum = m_1
          }
        }
        proportion_simes = c(proportion_simes,simes_sum/m_1)
      }
      proportion_sidak = mean(proportion_sidak[-1])
      proportion_simes = mean(proportion_simes[-1])
      sidak = c(sidak,proportion_sidak)
      simes = c(simes,proportion_simes)
    }
    plot(sidak[-1])
    points(abs(1-simes[-1]),col= "red")
  }
}



### Sidak under dependence
# Under independence, Sidak multiple test controls FWER. 
# Consider test statistics Z_i s are jointly normal
# Covariance matrix has 1's on the diagonal.
# Find situation where Sidak is unable to control FWER
require("MASS")
power = c()
alpha = 0
for(m in 3:10){
  beta = 1/(2*m)
  varmatrix = matrix(-beta,m,m)
  for(i in 1:m){
    varmatrix[i,i] = 1
  }
  for(b in 1:100){
    sum = 0
    nonzero = seq(1,floor(m/2),1)
    zero = rep(0,ceiling(m/2))
    mu = c(nonzero, zero)
    samplez = mvrnorm(n = 1, mu, varmatrix)
    alphastar = 1-(1-0.05)^(1/m)
    alphastar = -qnorm(alphastar)
    for(i in 2:m){
      sum = sum + sum(samplez[i] > alphastar)
    }
    power = c(power,sum/m)
  }
  power = mean(power)
  alpha = c(alpha, power)
}
alpha

# the sample is generated by half of mean zero and half of mean from 1 to 10
# choose alpha to be 0.05
# when alpha > 0.05, it means FWER cannot be controlled

  

